<?php

/**
 * @file category.inc
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

?>

<div class="listing-type-grid catalog-listing">
	<div class="category-head">
		<h1>Thường thức - Đời sống</h1>
	</div>
	<p class="category-description">Sách về thường thức - đời sống: nấu ăn, pha chế thức uống, làm vườn, nhà
		cửa, phong thuỷ, nuôi dạy con, cắm hoa, đời sống vợ chồng, chăm sóc thai
		kỳ</p>
	<table class="pager" cellspacing="0">
		<tbody>
			<tr>
				<!--<td nowrap>
                            Các item 1 tới 24 của 839 tổng số                        </td>-->
				<!-- View By -->
				<td nowrap="">Xem như:
					<strong>Lưới</strong>&nbsp;
					<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?mode=list">Danh sách</a>&nbsp;</td>
				<td class="sort-by" nowrap="">Xếp theo
					<select onchange="setLocation(this.value)">
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=entity_id"
						selected="selected">Mới nhập</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=position">Vị trí</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=name">Name</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=price">Giá</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=publication_date">Ngày xuất bản</option>
					</select>
					<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=entity_id"><img src="http://tiki.vn/skin/frontend/default/tiki/images/sort_desc_arrow.gif" alt="Xếp theo chiều tăng dần" class="v-middle"></a>
				</td>
				<td class="pages" nowrap="">
					<table class="pager" cellspacing="0">
						<tbody>
							<tr>
								<td class="pages">
									<strong>Trang:</strong>
									<ol>
										<li>
											<span class="on">1</span>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=2">2</a>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=3">3</a>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=4">4</a>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=5">5</a>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=2"><img src="http://tiki.vn/skin/frontend/default/tiki/images/pager_arrow_right.gif" alt="Trang tiếp theo"></a>
										</li>
									</ol>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
				<td class="a-right" nowrap="">Hiển thị
					<select onchange="setLocation(this.value)">
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?limit=24"
						selected="selected">24</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?limit=36">36</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?limit=48">48</option>
					</select>trên trang</td>
			</tr>
		</tbody>
	</table>
	<div class="listing-type-grid catalog-listing">
		<ul class="grid-row odd">
			<li class="item first">
				<p class="product-image" style="position: relative;">
					<span class="slOf_flag">
						<span class="slOf_sale">-10%</span>
					</span>
					<a href="http://tiki.vn/lam-giau-tu-mang-xa-hoi.html?ref=316c862c870c871"
					title="Làm Giàu Từ Mạng Xã Hội">
                                <img src="http://tiki.vn/media/catalog/product/cache/1/small_image/140x196/9df78eab33525d08d6e5fb8d27136e95/1/2/120711_mangxahoi.jpg" width="140" height="196" alt="Làm Giàu Từ Mạng Xã Hội" title="Làm Giàu Từ Mạng Xã Hội">
                            </a>
				</p>
				<h2 class="product-name">
					<a href="http://tiki.vn/lam-giau-tu-mang-xa-hoi.html?ref=316c862c870c871"
					title="Làm Giàu Từ Mạng Xã Hội">
                                Làm Giàu Từ Mạng Xã Hội                            </a>
				</h2>
				<!--Cover-->
				<p class="cover-books">Bìa Mềm</p>
				<!--End-->
				<div class="price-box">
					<span class="regular-price price">Đặt trước</span>
					<div class="price-block">
						<span class="special-price">
							<span class="price" id="product-price-44626">62.100&nbsp;₫
								<!--price43-->
							</span>
						</span>
						<span class="old-price">
							<span class="price" id="old-price-44626">69.000&nbsp;₫
								<!--price39-->
							</span>
						</span>
					</div>
				</div>
				<div class="points-prediction"></div>
			</li>
			<li class="item">
				<p class="product-image" style="position: relative;">
					<span class="slOf_flag">
						<span class="slOf_sale">-10%</span>
					</span>
					<a href="http://tiki.vn/khach-hang-muon-mua-gi.html?ref=316c862c870c871"
					title="Khách Hàng Muốn Mua Gì">
                                <img src="http://tiki.vn/media/catalog/product/cache/1/small_image/140x196/9df78eab33525d08d6e5fb8d27136e95/1/2/120808_khachhang.jpg" width="140" height="196" alt="Khách Hàng Muốn Mua Gì" title="Khách Hàng Muốn Mua Gì">
                            </a>
				</p>
				<h2 class="product-name">
					<a href="http://tiki.vn/khach-hang-muon-mua-gi.html?ref=316c862c870c871"
					title="Khách Hàng Muốn Mua Gì">
                                Khách Hàng Muốn Mua Gì                            </a>
				</h2>
				<!--Cover-->
				<p class="cover-books">Bìa Mềm</p>
				<!--End-->
				<div class="price-box">
					<span class="regular-price price">Đặt trước</span>
					<div class="price-block">
						<span class="special-price">
							<span class="price" id="product-price-44625">53.100&nbsp;₫
								<!--price43-->
							</span>
						</span>
						<span class="old-price">
							<span class="price" id="old-price-44625">59.000&nbsp;₫
								<!--price39-->
							</span>
						</span>
					</div>
				</div>
				<div class="points-prediction"></div>
			</li>
			<li class="item">
				<p class="product-image" style="position: relative;">
					<span class="slOf_flag">
						<span class="slOf_sale">-10%</span>
					</span>
					<a href="http://tiki.vn/nge-thuat-dam-phan.html?ref=316c862c870c871" title="Nghệ Thuật Đàm Phán">
                                <img src="http://tiki.vn/media/catalog/product/cache/1/small_image/140x196/9df78eab33525d08d6e5fb8d27136e95/1/2/120711_damphan.jpg" width="140" height="196" alt="Nghệ Thuật Đàm Phán" title="Nghệ Thuật Đàm Phán">
                            </a>
				</p>
				<h2 class="product-name">
					<a href="http://tiki.vn/nge-thuat-dam-phan.html?ref=316c862c870c871" title="Nghệ Thuật Đàm Phán">
                                Nghệ Thuật Đàm Phán                            </a>
				</h2>
				<!--Cover-->
				<p class="cover-books">Bìa Mềm</p>
				<!--End-->
				<div class="price-box">
					<div class="price-block">
						<span class="special-price">
							<span class="price" id="product-price-44623">48.600&nbsp;₫
								<!--price43-->
							</span>
						</span>
						<span class="old-price">
							<span class="price" id="old-price-44623">54.000&nbsp;₫
								<!--price39-->
							</span>
						</span>
					</div>
				</div>
				<div class="points-prediction"></div>
			</li>
			<li class="item last">
				<p class="product-image" style="position: relative;">
					<span class="slOf_flag">
						<span class="slOf_sale">-10%</span>
					</span>
					<a href="http://tiki.vn/ra-quyet-dinh-thong-minh.html?ref=316c862" title="Ra Quyết Định Thông Minh">
                                <img src="http://tiki.vn/media/catalog/product/cache/1/small_image/140x196/9df78eab33525d08d6e5fb8d27136e95/1/2/120711_thongminh.jpg" width="140" height="196" alt="Ra Quyết Định Thông Minh" title="Ra Quyết Định Thông Minh">
                            </a>
				</p>
				<h2 class="product-name">
					<a href="http://tiki.vn/ra-quyet-dinh-thong-minh.html?ref=316c862" title="Ra Quyết Định Thông Minh">
                                Ra Quyết Định Thông Minh                            </a>
				</h2>
				<!--Cover-->
				<p class="cover-books">Bìa Mềm</p>
				<!--End-->
				<div class="price-box">
					<div class="price-block">
						<span class="special-price">
							<span class="price" id="product-price-44622">45.000&nbsp;₫
								<!--price43-->
							</span>
						</span>
						<span class="old-price">
							<span class="price" id="old-price-44622">50.000&nbsp;₫
								<!--price39-->
							</span>
						</span>
					</div>
				</div>
				<div class="points-prediction"></div>
			</li>
		</ul>
		<ul class="grid-row last even">
			<li class="item first">
				<p class="product-image" style="position: relative;">
					<span class="slOf_flag">
						<span class="slOf_sale">-10%</span>
					</span>
					<a href="http://tiki.vn/phong-chong-ung-thu.html?ref=316c862c863" title="Phòng Chống Ung Thư">
                                <img src="http://tiki.vn/media/catalog/product/cache/1/small_image/140x196/9df78eab33525d08d6e5fb8d27136e95/p/h/ph_ng_ch_ng_ung_th_.jpg" width="140" height="196" alt="Phòng Chống Ung Thư" title="Phòng Chống Ung Thư">
                            </a>
				</p>
				<h2 class="product-name">
					<a href="http://tiki.vn/phong-chong-ung-thu.html?ref=316c862c863" title="Phòng Chống Ung Thư">
                                Phòng Chống Ung Thư                            </a>
				</h2>
				<!--Cover-->
				<p class="cover-books">Bìa Mềm</p>
				<!--End-->
				<div class="price-box">
					<div class="price-block">
						<span class="special-price">
							<span class="price" id="product-price-43437">108.000&nbsp;₫
								<!--price43-->
							</span>
						</span>
						<span class="old-price">
							<span class="price" id="old-price-43437">120.000&nbsp;₫
								<!--price39-->
							</span>
						</span>
					</div>
				</div>
				<div class="points-prediction"></div>
			</li>
			<li class="item">
				<p class="product-image" style="position: relative;">
					<span class="slOf_flag">
						<span class="slOf_sale">-10%</span>
					</span>
					<a href="http://tiki.vn/co-the-va-suc-khoe-con-nguoi.html?ref=316c862c866c873c885"
					title="Cơ Thể Và Sức Khỏe Con Người">
                                <img src="http://tiki.vn/media/catalog/product/cache/1/small_image/140x196/9df78eab33525d08d6e5fb8d27136e95/c/o/co-the-va-suc-khoe-con-nguoi.jpg" width="140" height="196" alt="Cơ Thể Và Sức Khỏe Con Người" title="Cơ Thể Và Sức Khỏe Con Người">
                            </a>
				</p>
				<h2 class="product-name">
					<a href="http://tiki.vn/co-the-va-suc-khoe-con-nguoi.html?ref=316c862c866c873c885"
					title="Cơ Thể Và Sức Khỏe Con Người">
                                Cơ Thể Và Sức Khỏe Con ...                            </a>
				</h2>
				<!--Cover-->
				<p class="cover-books">Bìa Cứng</p>
				<!--End-->
				<div class="price-box">
					<div class="price-block">
						<span class="special-price">
							<span class="price" id="product-price-43389">72.000&nbsp;₫
								<!--price43-->
							</span>
						</span>
						<span class="old-price">
							<span class="price" id="old-price-43389">80.000&nbsp;₫
								<!--price39-->
							</span>
						</span>
					</div>
				</div>
				<div class="points-prediction"></div>
			</li>
			<li class="item">
				<p class="product-image" style="position: relative;">
					<span class="slOf_flag">
						<span class="slOf_sale">-10%</span>
					</span>
					<a href="http://tiki.vn/cac-mon-dua-chua-do-nguoi-tron-cuon-hon-hop.html?ref=316c862c865"
					title="Các Món Dưa Chua Đồ Nguội - Trộn Cuốn Hỗn Hợp">
                                <img src="http://tiki.vn/media/catalog/product/cache/1/small_image/140x196/9df78eab33525d08d6e5fb8d27136e95/c/a/cac-mon-dua-chua-do-nguoi_1.jpg" width="140" height="196" alt="Các Món Dưa Chua Đồ Nguội - Trộn Cuốn Hỗn Hợp" title="Các Món Dưa Chua Đồ Nguội - Trộn Cuốn Hỗn Hợp">
                            </a>
				</p>
				<h2 class="product-name">
					<a href="http://tiki.vn/cac-mon-dua-chua-do-nguoi-tron-cuon-hon-hop.html?ref=316c862c865"
					title="Các Món Dưa Chua Đồ Nguội - Trộn Cuốn Hỗn Hợp">
                                Các Món Dưa Chua Đồ Nguội ...                            </a>
				</h2>
				<!--Cover-->
				<p class="cover-books">Bìa Mềm</p>
				<!--End-->
				<div class="price-box">
					<div class="price-block">
						<span class="special-price">
							<span class="price" id="product-price-43284">45.000&nbsp;₫
								<!--price43-->
							</span>
						</span>
						<span class="old-price">
							<span class="price" id="old-price-43284">50.000&nbsp;₫
								<!--price39-->
							</span>
						</span>
					</div>
				</div>
				<div class="points-prediction"></div>
			</li>
			<li class="item last">
				<p class="product-image" style="position: relative;">
					<span class="slOf_flag">
						<span class="slOf_sale">-10%</span>
					</span>
					<a href="http://tiki.vn/cac-mon-an-che-bien-tu-rong-bien-moi-la-va-bo-duong.html?ref=316c862c865"
					title="Các Món Ăn Chế Biến Từ Rong Biển Mới Lạ &amp; Bổ Dưỡng">
                                <img src="http://tiki.vn/media/catalog/product/cache/1/small_image/140x196/9df78eab33525d08d6e5fb8d27136e95/c/a/cac-mon-an-che-bien-tu-rong-bien_1.jpg" width="140" height="196" alt="Các Món Ăn Chế Biến Từ Rong Biển Mới Lạ &amp; Bổ Dưỡng" title="Các Món Ăn Chế Biến Từ Rong Biển Mới Lạ &amp; Bổ Dưỡng">
                            </a>
				</p>
				<h2 class="product-name">
					<a href="http://tiki.vn/cac-mon-an-che-bien-tu-rong-bien-moi-la-va-bo-duong.html?ref=316c862c865"
					title="Các Món Ăn Chế Biến Từ Rong Biển Mới Lạ &amp; Bổ Dưỡng">
                                Các Món Ăn Chế Biến Từ ...                            </a>
				</h2>
				<!--Cover-->
				<p class="cover-books">Bìa Mềm</p>
				<!--End-->
				<div class="price-box">
					<div class="price-block">
						<span class="special-price">
							<span class="price" id="product-price-42941">28.800&nbsp;₫
								<!--price43-->
							</span>
						</span>
						<span class="old-price">
							<span class="price" id="old-price-42941">32.000&nbsp;₫
								<!--price39-->
							</span>
						</span>
					</div>
				</div>
				<div class="points-prediction"></div>
			</li>
		</ul>
		<script type="text/javascript">
		decorateGeneric($$('.grid-row'), ['last', 'odd', 'even']);
		</script>
	</div>
	<div style="border-bottom:1px solid #e2e2e2;"></div>
	<table class="pager" cellspacing="0">
		<tbody>
			<tr>
				<!--<td nowrap>
                            Các item 1 tới 24 của 839 tổng số                        </td>-->
				<!-- View By -->
				<td nowrap="">Xem như:
					<strong>Lưới</strong>&nbsp;
					<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?mode=list">Danh sách</a>&nbsp;</td>
				<td class="sort-by" nowrap="">Xếp theo
					<select onchange="setLocation(this.value)">
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=entity_id"
						selected="selected">Mới nhập</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=position">Vị trí</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=name">Name</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=price">Giá</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=publication_date">Ngày xuất bản</option>
					</select>
					<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?dir=asc&amp;order=entity_id"><img src="http://tiki.vn/skin/frontend/default/tiki/images/sort_desc_arrow.gif" alt="Xếp theo chiều tăng dần" class="v-middle"></a>
				</td>
				<td class="pages" nowrap="">
					<table class="pager" cellspacing="0">
						<tbody>
							<tr>
								<td class="pages">
									<strong>Trang:</strong>
									<ol>
										<li>
											<span class="on">1</span>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=2">2</a>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=3">3</a>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=4">4</a>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=5">5</a>
										</li>
										<li>
											<a href="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?p=2"><img src="http://tiki.vn/skin/frontend/default/tiki/images/pager_arrow_right.gif" alt="Trang tiếp theo"></a>
										</li>
									</ol>
								</td>
							</tr>
						</tbody>
					</table>
				</td>
				<td class="a-right" nowrap="">Hiển thị
					<select onchange="setLocation(this.value)">
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?limit=24" selected="selected">24</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?limit=36">36</option>
						<option value="http://tiki.vn/sach-truyen-tieng-viet/thuong-thuc-doi-song.html?limit=48">48</option>
					</select>trên trang</td>
			</tr>
		</tbody>
	</table>
</div>